package:
  name: rmap
  version: "1.0"

build:
  noarch: python
  number: 0

source:
  git_url: https://github.com/GunzIvan28/rMAP.git

requirements:
  build:
    - git
    - setuptools
  run:
    - abricate >=1.0.1
    - fastqc >=0.11.9
    - multiqc >=1.9
    - snippy >=4.3.6
    - snpeff <=4.5
    - ncbi-amrfinderplus >=3.8.4
    - prokka >=1.14.6
    - prodigal >=2.6.3
    - freebayes >=1.3.2
    - unicycler >=0.4
    - mlst >=2.19.0
    - assembly-stats >=1.0.1
    - sra-tools <=2.10.8
    - bwa >=0.7.17
    - kleborate >=1.0.0
    - mafft >=7.471
    - quast >=5.0.2
    - r-base >=4.0.2
    - trimmomatic >=0.39
    - megahit >=1.2.9
    - parallel >=20200722
    - prinseq >=0.20.4
    - shovill >=1.0.9
    - vt <=2015.11.10
    - fasttree >=2.1.10
    - samclip >=0.4.0
    - nextflow >=20.07.1
    - any2fasta >=0.4.2
    - python >=3.7,<3.8
    - biopython.convert >=1.0.3
    - iqtree >=2.0.3
    - bmge >=1.12
    - samtools >=1.9
    - roary >=3.13.0
    - ismapper >=2.0.1
    - lxml >=4.5.2
    - cairosvg >=2.4.2
about:
  summary: Bacterial analysis Toolbox for profiling the Resistome of ESKAPE pathogens using WGS
  home: https://github.com/GunzIvan28/rMAP
  license: LGPL-3.0
  license_file: LICENSE

extra:
  maintainers:
    - Ivan Sserwadda
    - Gerald Mboowa
